### ISSUE TITLE
안녕하세요

### ISSUE THREAD

**Issue by JipDol2** [Lagom92/Todal_movie#2]
안녕하세요.
전 현재 대학을 다니고 있는 3학년 학생입니다. 
다름이 아니라 이번 학기에 오픈소스에 참여해야 되는 과제를 수행해야되는데 혹시 이 프로젝트에 같이 동참해도 될까요?

별개로 웹 사이트 링크와 소스는 어느 디렉토리에 구현이 되어있는지를 문서화 해서 작성해 주실수 있으실까요??

**Comment by Lagom92** [comment]
죄송합니다
해당 프로젝트는 진행 하지 않고 있습니다.
